apiVersion: v1
kind: Service
metadata:
  labels:
    app: apache
  name: apache-clusterip
spec:
  selector:
    app: apache
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  type: ClusterIP