apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-node2
  template:
    metadata:
        labels:
          app: hello-node2
    spec:
      containers:
        - name: hello-node2
          image: libp/nginx:stream
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"

