apiVersion: v1
kind: Service
metadata:
  labels:
    app: apache
  name: apache-nodeport
spec:
  selector:
    app: apache
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  type: NodePort