apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache
  name: apache
spec:
  replicas: 6
  selector:
    matchLabels:
      app: apache
  strategy: {}
  template:
    metadata:
      labels:
        app: apache
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
      - image: docker.m.daocloud.io/libp/apache:v3
        name: apache
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apache
  name: apache
spec:
  type: NodePort
  selector:
    app: apache
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30080

