apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - commcand:
    - sh
    - date
    image: docker.m.daocloud.io/busybox
    name: busybox
    resources: 
      limits:
        cpu: "0.5"
        memory: "256Mi"
      requests:
        cpu: "0.1"
        memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}