apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: docker.m.daocloud.io/libp/nginx:v3
    name: nginx
    ports:
    - containerPort: 80
    resources: 
      limits:
        cpu: "0.5"
        memory: "256Mi"
      requests:
        cpu: "0.1"
        memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
