# Create a new nginx ingress resource as follows:
#   Name: ping 
#   Namespace: ing-internal
#   Exposing service hi on path /hi using service port 5678

# tips: The availability of service hi can be checked using the following commands,which should retun hi: 
# curl -KL <INTERNAL_IP>/hi

# 分数：7

# 解题

# 关键字：ingress
# 链接：https://kubernetes.io/zh-cn/docs/concepts/services-networking/ingress/


# ping.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ping
  namespace: ing-internal
spec:
  rules:
  - http:
      paths:
      - path: /hi
        pathType: Prefix
        backend:
          service:
            name: hi
            port:
              number: 5678


# kubectl create ingress ping -n ing-internal --rule=/hi=hi:5678 --dry-run=client -o yaml