# Create a pod named kucc8 with a single app container for each of the following images running inside(there may be between 1 and 4 images specified):

# nginx + redis + memcached + consul
# 分数：4

# 解题

# 关键字：
# 链接：

# kubectl run kucc8 --image=nginx --dry-run=client -o yaml

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kucc8
  name: kucc8
spec:
  containers:
  - image: nginx
    name: nginx
  - image: redis
    name: redis
  - image: memcached
    name: memcached
  - image: consul
    name: consul
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

# kubectl apply -f 11.yaml